# Generated by Django 3.2.7 on 2022-03-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20220225_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('message_type', models.CharField(choices=[('Общие вопросы', 'Общие вопросы'), ('Претензии|Жалобы|Замечания к работе', 'Претензии|Жалобы|Замечания к работе'), ('Диспетчерская служба', 'Диспетчерская служба'), ('Тепловая инспекция', 'Тепловая инспекция')], default='Выберите тип сообщения', max_length=50, verbose_name='Тип сообщения')),
                ('message', models.TextField(max_length=1000, verbose_name='Текст сообщения')),
                ('income_date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'Элемент обратной связи',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ['id', 'name', 'email'],
            },
        ),
        migrations.AlterModelOptions(
            name='gvs',
            options={'ordering': ['id', 'region', 'street', 'build'], 'verbose_name': 'Элемент списка', 'verbose_name_plural': 'Список домов Северного и Южного сетевых районов, в которых отсутствует ГВС'},
        ),
        migrations.AlterField(
            model_name='gvs',
            name='region',
            field=models.CharField(choices=[('Северный сетевой район', 'Северный сетевой район'), ('Южный сетевой район', 'Южный сетевой район')], max_length=50, verbose_name='Сетевой район'),
        ),
    ]
