# Generated by Django 3.2.7 on 2022-04-10 15:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_gvs_rem_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='gvs',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='gvs',
            name='rem_obj',
            field=models.CharField(default='', max_length=50, verbose_name='ТК,НО, ЦТП'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Контент'),
        ),
    ]
